export default defineEventHandler(async () => {
    // Fetch your common data
    const common = await $fetch('/api/common').catch(() => ({}));
    return [
        {
            id: 1,
            plan_ttl_img: "/assets/images/mw/premium.svg",
            plan_ttl_img_alt: "Ideal for beginners and bloggers",
            title: common?.plansName?.web_1,
            subtitle: "Ideal for beginners and bloggers.",
            strike_price: `${common.currencySymbol}${common.strikePrice?.web_1?.[1]}"mo"`,
            price: `${common.currencySymbol}${common.price?.web_1?.[1]}"mo"`,
            save: `Save ${common.getDiscount?.('web_hosting')}%`,
            buy_link: "https://www.milesweb.in/checkout",
            billingcycle: "quadrennially",
            free_months: "<p>+3 months free</p>",
            category: "Shared Hosting",
            HighestBilling: "4 Years",
            features: [
                { label: '<b>25</b> websites', tooltip: 'The number of websites that you can host in your web hosting account.' },
                { label: '<b>100</b> GB NVMe storage', tooltip: 'Our storage is based on modern solid-state drives. Your website will perform 200% better as compared to the regular drives with the specified storage amount.' },
                { label: '<b>Free</b> domain for 1 year', tooltip: 'Choose a Premium plan for 1, 2, or 4 years and receive one complimentary domain (.COM, .IN, or .CO.IN) for the first year. Select any single extension; standard renewal rates apply from the second year. This offer cannot be customized.', freeDomain: false },
                { label: '<b>100</b> mailboxes - Free', tooltip: 'Create up to 100 mailboxes with 1GB storage each—free and included in your hosting plan. No extra charges. Ideal for personal or business use.' },
                { label: '<b>Free SSL</b> for every website', tooltip: 'We secure all supported websites on your plan with free, automated SSL certificates. No validation email required, auto-renewed, and trusted by major browsers.' },
                { label: 'Stay secure with daily backups', },
                { label: '<b>Free</b> website migration', tooltip: 'We provide a free migration service to help transfer your website from your previous provider to ours. We migrate your complete website files, folders, databases, and emails.' },
                { label: '<span class="plan-txt-b">AI website builder</span>', tooltip: 'AI builds your full website with content in minutes. No skills needed—try it now!' },
                { label: 'Managed WordPress hosting', tooltip: 'MilesWeb’s managed WordPress hosting provides a hands-free experience with tools like one-click staging, automatic updates, WP-CLI, Git, SSH, and PHP version control—perfect for hassle-free WordPress development and management.' },
                { label: 'Complete site protection', tooltip: 'Our malware scan tool scans your website for malware, quarantines the infected files, and cleans them automatically. It also generates a detailed report of the findings, ensuring your website remains safe and secure.' },
                { label: 'Website speed optimizer with CDN', tooltip: 'Cloudflare CDN (Content Delivery Network) boosts your website’s speed by caching content on a global network of servers and delivering it from the location nearest to each visitor. With built-in tools and advanced features, we ensure your website gets faster load times.' },
                { label: '24/7 Priority support', tooltip: false },
                { label: '<b>India</b> server location', tooltip: 'Your website is proudly hosted on Indian servers — ensuring faster performance for local visitors and supporting the Swadeshi digital movement.' },
            ],
            hidden_features: {
                "Managed WordPress": [
                    { label: '<b>Free</b> 1-click WordPress install', tooltip: 'Easily install WordPress, including other popular apps like Laravel, PrestaShop, and over 400 other such applications, with just a single click' },
                    { label: '<b>Free</b> 1-click Google integration', tooltip: 'Connect to top-line Google services like Google Webmaster, GA4, and AdSense with just a single click.' },
                    { label: '<b>Free</b> pre-built templates', tooltip: 'Access to diverse WordPress ready-made templates, fully configurable to fit your needs.' },
                    { label: 'WordPress acceleration (LiteSpeed)', tooltip: 'Our hosting is powered by LiteSpeed Cache for WordPress. The server-level cache is equipped with optimization features and can significantly improve the loading speed of a website.' },
                    { label: 'WordPress multisite', tooltip: 'Develop and operate multiple websites with one WordPress installation setup.' },
                    { label: 'WordPress vulnerabilities scanner', tooltip: 'Enjoy redundant WordPress vulnerabilities scanner, a tool that automatically scans your WordPress website for known security vulnerabilities. It helps you identify and fix threats promptly.' },
                    { label: 'WordPress autoupdates', tooltip: 'With the seamless auto-update WordPress feature, get the benefit of automatically updated core, themes, plugins, and more. ' },
                    { label: 'WordPress staging tool', tooltip: 'Preview all your changes and updates in a staging environment before launching them on your live site.' },
                    { label: 'WP-CLI and SSH', tooltip: 'It is a set of command-line tools to manage the WordPress installation. It can be used for configuring multisite installs, updating plugins, and more without the help of a web browser.' },
                    { label: 'Object cache for WordPress', tooltip: 'Object caching is a method of saving database query results. Thus, the server swiftly retrieves them when needed again, improving WordPress website response times.' },
                    { label: 'Starter WooCommerce', tooltip: 'Ideal for simple websites with high-scalability features. You can focus on building your brand and keeping your online store streamlined to meet basic needs.' },
                ],
                'Developer\'s feature': [
                    { label: 'PHP', tooltip: 'Get PHP scripting language versions installed on our servers. You can select the PHP version (4.4 to 8.3) from your control panel.' },
                    { label: 'CodeIgniter', tooltip: false },
                    { label: 'Laravel', tooltip: false },
                    { label: 'Node.js', tooltip: false, cross: true },
                    { label: 'Python', tooltip: false, cross: true },
                    { label: 'Django', tooltip: false, cross: true },
                    { label: 'GIT access', tooltip: 'Easily manage, clone, view, and deploy Git repositories within your control panel. Git integration enables efficient project management, editing, and syncing across multiple branches using the powerful version control capabilities of Git.' },
                ],
                'Security': [
                    { label: 'Web application firewall', tooltip: 'Secures your website from malicious attacks such as Cross-site Scripting (XSS), SQL injection, Local File Include, XML-RPC DDOS Attack, Remote File Include, etc.' },
                    { label: 'Secure access manager', tooltip: 'We have a robust system to control the network’s resources and application access. It is the secure access manager that ensures only authorized users get access to data and services.' },
                    { label: 'Anycast nameservers', tooltip: 'Anycast nameservers are a set of geographically dispersed servers using the same IP address. These nameservers bring high availability and rapid DNS resolution for users located throughout the world.' },
                    { label: 'Enhanced DDoS protection', tooltip: 'DDoS protection involves advanced measures of security to protect against Distributed Denial of Service (DDoS) attacks, which overwhelm a network or server with exaggerated traffic.' },
                ],
                'Service and support': [
                    { label: '30-day money-back guarantee', tooltip: 'If you aren\'t satisfied with our services, you can ask for a refund within 30 days of the service purchase.' },
                    { label: '24/7/365 customer support', tooltip: 'We are available 24/7/365 to resolve your issues promptly and professionally. Contact our customer support team via email or live chat.' },
                    { label: '99.9% uptime', tooltip: 'We offer a record maximum uptime that helps to keep your website up and running.' },
                ],
                'Technical details': [
                    { label: '<b>5,00,000</b> files & directories (inodes)', tooltip: 'File inodes are the fundamental unit of a file system. In simple terms, it stores information about a file or directory that runs on your server.' },
                    { label: '<b>40</b> PHP workers', tooltip: 'PHP workers are similar to the engine handling website requests and page buildings. More PHP workers mean faster and more efficient tasks, leading to smoother browsing experiences.' },
                    { label: '<b>~30,000</b> visits monthly', tooltip: 'The monthly visit number represents the estimated amount of traffic your websites can manage. Select your hosting plan according to the total number of visitors you expect across all your websites. ' },
                    { label: '<b>100</b> subdomains', tooltip: 'This number indicates how many subdomains you can create not only from your primary domain but also from any additional domains. Moreover, subdomains can be directed to any subdirectory within your hosting account.' },
                    { label: '<b>50</b> MySQL max user connections', tooltip: 'Using this limit, know how many simultaneous database connections can be made for a seamless hosting experience.' },
                    { label: '<b>350</b> databases', tooltip: 'This specifies the maximum number of individual databases you can create and manage within a single hosting account, providing developers with ample flexibility and scalability for their database-driven applications.' },
                    { label: '<b>Unlimited</b> FTP accounts', tooltip: 'Keep track of visitors that are logged into your site via FTP. It also allows you to terminate FTP connections to restrict file access to unauthorized users.' },
                    { label: '<b>Unlimited</b> cronjobs', tooltip: 'Cronjobs helps you schedule the execution of commands or scripts on a server at fixed intervals, dates, or times. The more cron jobs by your side, the maximum number of tasks you can schedule simultaneously.' },
                    { label: 'Multiple PHP versions', tooltip: 'Get PHP scripting language versions installed on our servers. You can select the PHP version (4.4 to 8.3) from your control panel.' },
                    { label: 'SSH access', tooltip: 'SSH offers secure, encrypted access to your hosting account, allowing safe file transfers, database handling, and SFTP functionality. It’s ideal for developers needing direct and protected server-level access for advanced operations.' },
                    { label: 'DNS management', tooltip: 'Create and edit all types of DNS records, including CNAME, A, TXT, MX, and SRV for your domains as well as subdomains.' },
                    { label: 'Cache manager', tooltip: 'Easily store copies of your files in a cache or temporary storage location so that they can be accessed more quickly.' },
                    { label: '<b>mPanel</b> control panel', tooltip: 'MilesWeb’s all-in-one control panel to manage your hosting, domains, emails, and sites with ease.' },
                    { label: '<b>2 GB</b> RAM', tooltip: 'The amount of memory offered with each hosting plan.' },
                    { label: '<b>2</b> CPU Cores', tooltip: 'A CPU’s processor is called a CPU core. It is the number of CPU cores offered with our web hosting plans.' },
                    { label: '<b>12 MBPS</b> IO Limit', tooltip: 'Represents the disk input and output limit.' },
                    { label: 'Unmetered bandwidth', tooltip: 'Get an unrestricted amount of data transferred between the visitors and your website. We provide unlimited data transfer for you to host all types of websites and grow independently to gain more visitors.' },
                ],
                'AI tools included': [
                    { label: 'AI website builder', tooltip: false },
                    { label: 'AI image generator', tooltip: false },
                    { label: 'AI writer', tooltip: false },
                    { label: 'AI blog generator', tooltip: false },
                ],
            }
        },
        {
            id: 2,
            plan_ttl_img: "/assets/images/mw/business.svg",
            plan_ttl_img_alt: "Great for startups and agencies",
            title: common?.plansName?.web_2,
            subtitle: "Great for startups and agencies.",
            strike_price: `${common.currencySymbol}${common.strikePrice?.web_2?.[1]}"mo"`,
            price: `${common.currencySymbol}${common.price?.web_2?.[1]}"mo"`,
            save: `Save ${common.getDiscount?.('web_hosting')}%`,
            buy_link: "https://www.milesweb.in/checkout",
            billingcycle: "quadrennially",
            free_months: "<p>+3 months free</p>",
            category: "Shared Hosting",
            HighestBilling: "4 Years",
            features: [
                { label: '<b>50</b> websites', tooltip: 'The number of websites that you can host in your web hosting account.' },
                { label: '<b>200</b> GB NVMe storage', tooltip: 'Our storage is based on modern solid-state drives. Your website will perform 200% better as compared to the regular drives with the specified storage amount.' },
                { label: '<b>Free</b> domain for 1 year', tooltip: 'Choose a Business plan for 1, 2, or 4 years and receive one complimentary domain (.COM, .IN, or .CO.IN) for the first year. Select any single extension; standard renewal rates apply from the second year. This offer cannot be customized.', freeDomain: false },
                { label: '<b>125</b> mailboxes - Free', tooltip: 'Create up to 125 mailboxes with 1GB storage each—free and included in your hosting plan. No extra charges. Ideal for personal or business use.' },
                { label: '<b>Free SSL</b> for every website', tooltip: 'We secure all supported websites on your plan with free, automated SSL certificates. No validation email required, auto-renewed, and trusted by major browsers.' },
                { label: 'Stay secure with daily backups', },
                { label: '<b>Free</b> website migration', tooltip: 'We provide a free migration service to help transfer your website from your previous provider to ours. We migrate your complete website files, folders, databases, and emails.' },
                { label: '<span class="plan-txt-b">AI website builder</span>', tooltip: 'AI builds your full website with content in minutes. No skills needed—try it now!' },
                { label: 'Managed WordPress hosting', tooltip: 'MilesWeb’s managed WordPress hosting provides a hands-free experience with tools like one-click staging, automatic updates, WP-CLI, Git, SSH, and PHP version control—perfect for hassle-free WordPress development and management.' },
                { label: 'Complete site protection', tooltip: 'Our malware scan tool scans your website for malware, quarantines the infected files, and cleans them automatically. It also generates a detailed report of the findings, ensuring your website remains safe and secure.' },
                { label: 'Website speed optimizer with CDN', tooltip: 'Cloudflare CDN (Content Delivery Network) boosts your website’s speed by caching content on a global network of servers and delivering it from the location nearest to each visitor. With built-in tools and advanced features, we ensure your website gets faster load times.' },
                { label: '24/7 Priority support', tooltip: false },
                { label: '<b>India</b> server location', tooltip: 'Your website is proudly hosted on Indian servers — ensuring faster performance for local visitors and supporting the Swadeshi digital movement.' }
            ],
            hidden_features: {
                "Managed WordPress": [
                    { label: '<b>Free</b> 1-click WordPress install', tooltip: 'Easily install WordPress, including other popular apps like Laravel, PrestaShop, and over 400 other such applications, with just a single click' },
                    { label: '<b>Free</b> 1-click Google integration', tooltip: 'Connect to top-line Google services like Google Webmaster, GA4, and AdSense with just a single click.' },
                    { label: '<b>Free</b> pre-built templates', tooltip: 'Access to diverse WordPress ready-made templates, fully configurable to fit your needs.' },
                    { label: 'WordPress acceleration (LiteSpeed)', tooltip: 'Our hosting is powered by LiteSpeed Cache for WordPress. The server-level cache is equipped with optimization features and can significantly improve the loading speed of a website.' },
                    { label: 'WordPress multisite', tooltip: 'Develop and operate multiple websites with one WordPress installation setup.' },
                    { label: 'WordPress vulnerabilities scanner', tooltip: 'Enjoy redundant WordPress vulnerabilities scanner, a tool that automatically scans your WordPress website for known security vulnerabilities. It helps you identify and fix threats promptly.' },
                    { label: 'WordPress autoupdates', tooltip: 'With the seamless auto-update WordPress feature, get the benefit of automatically updated core, themes, plugins, and more. ' },
                    { label: 'WordPress staging tool', tooltip: 'Preview all your changes and updates in a staging environment before launching them on your live site.' },
                    { label: 'WP-CLI and SSH', tooltip: 'It is a set of command-line tools to manage the WordPress installation. It can be used for configuring multisite installs, updating plugins, and more without the help of a web browser.' },
                    { label: 'Object cache for WordPress', tooltip: 'Object caching is a method of saving database query results. Thus, the server swiftly retrieves them when needed again, improving WordPress website response times.' },
                    { label: 'Basic WooCommerce', tooltip: 'Ideal for simple websites with high-scalability features. You can focus on building your brand and keeping your online store streamlined to meet basic needs.' },
                ],
                'Developer\'s feature': [
                    { label: 'PHP', tooltip: 'Get PHP scripting language versions installed on our servers. You can select the PHP version (4.4 to 8.3) from your control panel.' },
                    { label: 'CodeIgniter', tooltip: false },
                    { label: 'Laravel', tooltip: false },
                    { label: 'Node.js', tooltip: false, cross: true },
                    { label: 'Python', tooltip: false, cross: true },
                    { label: 'Django', tooltip: false, cross: true },
                    { label: 'GIT access', tooltip: 'Easily manage, clone, view, and deploy Git repositories within your control panel. Git integration enables efficient project management, editing, and syncing across multiple branches using the powerful version control capabilities of Git.' },
                ],
                'Security': [
                    { label: 'Web application firewall', tooltip: 'Secures your website from malicious attacks such as Cross-site Scripting (XSS), SQL injection, Local File Include, XML-RPC DDOS Attack, Remote File Include, etc.' },
                    { label: 'Secure access manager', tooltip: 'We have a robust system to control the network’s resources and application access. It is the secure access manager that ensures only authorized users get access to data and services.' },
                    { label: 'Anycast nameservers', tooltip: 'Anycast nameservers are a set of geographically dispersed servers using the same IP address. These nameservers bring high availability and rapid DNS resolution for users located throughout the world.' },
                    { label: 'Enhanced DDoS protection', tooltip: 'DDoS protection involves advanced measures of security to protect against Distributed Denial of Service (DDoS) attacks, which overwhelm a network or server with exaggerated traffic.' },
                ],
                'Service and support': [
                    { label: '30-day money-back guarantee', tooltip: 'If you aren\'t satisfied with our services, you can ask for a refund within 30 days of the service purchase.' },
                    { label: '24/7/365 customer support', tooltip: 'We are available 24/7/365 to resolve your issues promptly and professionally. Contact our customer support team via email or live chat.' },
                    { label: '99.9% uptime', tooltip: 'We offer a record maximum uptime that helps to keep your website up and running.' },
                ],
                'Technical details': [
                    { label: '<b>7,00,000</b> files & directories (inodes)', tooltip: 'File inodes are the fundamental unit of a file system. In simple terms, it stores information about a file or directory that runs on your server.' },
                    { label: '<b>100</b> PHP workers', tooltip: 'PHP workers are similar to the engine handling website requests and page buildings. More PHP workers mean faster and more efficient tasks, leading to smoother browsing experiences.' },
                    { label: '<b>~1,25,000</b> visits monthly', tooltip: 'The monthly visit number represents the estimated amount of traffic your websites can manage. Select your hosting plan according to the total number of visitors you expect across all your websites. ' },
                    { label: '<b>200</b> subdomains', tooltip: 'This number indicates how many subdomains you can create not only from your primary domain but also from any additional domains. Moreover, subdomains can be directed to any subdirectory within your hosting account.' },
                    { label: '<b>75</b> MySQL max user connections', tooltip: 'Using this limit, know how many simultaneous database connections can be made for a seamless hosting experience.' },
                    { label: '<b>350</b> databases', tooltip: 'This specifies the maximum number of individual databases you can create and manage within a single hosting account, providing developers with ample flexibility and scalability for their database-driven applications.' },
                    { label: '<b>Unlimited</b> FTP accounts', tooltip: 'Keep track of visitors that are logged into your site via FTP. It also allows you to terminate FTP connections to restrict file access to unauthorized users.' },
                    { label: '<b>Unlimited</b> cronjobs', tooltip: 'Cronjobs helps you schedule the execution of commands or scripts on a server at fixed intervals, dates, or times. The more cron jobs by your side, the maximum number of tasks you can schedule simultaneously.' },
                    { label: 'Multiple PHP versions', tooltip: 'Get PHP scripting language versions installed on our servers. You can select the PHP version (4.4 to 8.3) from your control panel.' },
                    { label: 'SSH access', tooltip: 'SSH offers secure, encrypted access to your hosting account, allowing safe file transfers, database handling, and SFTP functionality. It’s ideal for developers needing direct and protected server-level access for advanced operations.' },
                    { label: 'DNS management', tooltip: 'Create and edit all types of DNS records, including CNAME, A, TXT, MX, and SRV for your domains as well as subdomains.' },
                    { label: 'Cache manager', tooltip: 'Easily store copies of your files in a cache or temporary storage location so that they can be accessed more quickly.' },
                    { label: '<b>mPanel</b> control panel', tooltip: 'MilesWeb’s all-in-one control panel to manage your hosting, domains, emails, and sites with ease.' },
                    { label: '<b>3 GB</b> RAM', tooltip: 'The amount of memory offered with each hosting plan.' },
                    { label: '<b>3</b> CPU Cores', tooltip: 'A CPU’s processor is called a CPU core. It is the number of CPU cores offered with our web hosting plans.' },
                    { label: '<b>20 MBPS</b> IO Limit', tooltip: 'Represents the disk input and output limit.' },
                    { label: 'Unmetered bandwidth', tooltip: 'Get an unrestricted amount of data transferred between the visitors and your website. We provide unlimited data transfer for you to host all types of websites and grow independently to gain more visitors.' },
                ],
                'AI tools included': [
                    { label: 'AI website builder', tooltip: false },
                    { label: 'AI image generator', tooltip: false },
                    { label: 'AI writer', tooltip: false },
                    { label: 'AI blog generator', tooltip: false },
                ],
            }
        },
    ];
});
